window.ENARM_SCALE_CATALOG_DATA = [
  {
    id: "alvarado",
    name: "Alvarado",
    tracks: ["cirugia"],
    subtitle: "Apendicitis aguda",
    trigger: "Dolor en FID con sospecha de apendicitis.",
    hook: "MANTRELS",
    components: [
      "Migracion del dolor 1",
      "Anorexia 1",
      "Nausea o vomito 1",
      "Dolor en FID 2",
      "Rebote 1",
      "Fiebre 1",
      "Leucocitosis 2",
      "Neutrofilia 1"
    ],
    cutoffs: ["1-4 poco probable", "5-6 compatible", "7-8 probable", "9-10 muy probable"],
    pearl: "Los dos rubros de 2 puntos son dolor en FID y leucocitosis.",
    trap: "Neutrofilia vale 1; leucocitosis vale 2.",
    prompt: "Di la mnemotecnia, los 2 rubros de 2 puntos y el corte que la hace probable.",
    answer: "MANTRELS; dolor en FID y leucocitosis; desde 7 puntos la apendicitis es probable.",
    searchTerms: ["apendicitis mantrels mcburney abdomen agudo"]
  },
  {
    id: "ranson",
    name: "Ranson",
    tracks: ["cirugia"],
    subtitle: "Pancreatitis aguda",
    trigger: "Pancreatitis aguda cuando preguntan severidad clasica.",
    hook: "5 al ingreso + 6 a las 48 horas",
    components: [
      "Ingreso: edad >55, leucocitos >16000, glucosa >200, LDH >350, AST >250",
      "48 h: hematocrito -10%, BUN +5, calcio <8, PaO2 <60, deficit de base >4, liquidos >6 L"
    ],
    cutoffs: ["<3 suele ser leve", ">=3 severa", ">=6 mortalidad muy alta"],
    pearl: "La trampa clasica es que necesitas 48 horas para completarla.",
    trap: "Si el reactivo pide severidad temprana, piensa primero en BISAP.",
    prompt: "Que escala de pancreatitis te obliga a esperar 48 horas y cuales son sus 5 criterios de ingreso?",
    answer: "Ranson; edad, leucocitos, glucosa, LDH y AST al ingreso.",
    searchTerms: ["pancreatitis severidad 48 horas"]
  },
  {
    id: "bisap",
    name: "BISAP",
    tracks: ["cirugia"],
    subtitle: "Pancreatitis aguda temprana",
    trigger: "Pancreatitis aguda en las primeras 24 horas.",
    hook: "BUN - Impaired mental status - SIRS - Age - Pleural effusion",
    components: ["BUN >25", "Glasgow <15", "SIRS >=2", "Edad >60", "Derrame pleural"],
    cutoffs: ["0-2 menor riesgo", ">=3 alto riesgo"],
    pearl: "Sirve para severidad temprana sin esperar 48 horas.",
    trap: "Lipasa no entra a BISAP.",
    prompt: "Di las 5 letras de BISAP y el corte que prende alarmas.",
    answer: "BUN, estado mental, SIRS, edad y derrame pleural; >=3 preocupa.",
    searchTerms: ["pancreatitis bisap bun sirs"]
  },
  {
    id: "glasgow-blatchford",
    name: "Glasgow-Blatchford",
    tracks: ["cirugia", "medicina"],
    subtitle: "Sangrado digestivo alto",
    trigger: "Hematemesis o melena antes de endoscopia.",
    hook: "BUN, Hb, TA, pulso, melena, sincope, hepatopatia e IC",
    components: ["BUN", "Hemoglobina", "Presion sistolica", "Pulso", "Melena", "Sincope", "Hepatopatia", "Insuficiencia cardiaca"],
    cutoffs: ["0-1 muy bajo riesgo", ">1 requiere valoracion hospitalaria"],
    pearl: "Es pre-endoscopica y ayuda al triage inicial.",
    trap: "No la confundas con Rockall.",
    prompt: "Que escala usas antes de endoscopia y quien es muy bajo riesgo?",
    answer: "Glasgow-Blatchford; 0-1 es el grupo de menor riesgo.",
    searchTerms: ["melena hematemesis endoscopia triage gbs"]
  },
  {
    id: "wells-tep",
    name: "Wells para TEP",
    tracks: ["medicina"],
    subtitle: "Tromboembolia pulmonar",
    trigger: "Disnea brusca o dolor pleuritico con sospecha de TEP.",
    hook: "Dos rubros pesan 3",
    components: ["Signos de TVP 3", "TEP mas probable 3", "FC >100 1.5", "Inmovilizacion o cirugia 1.5", "TEP/TVP previo 1.5", "Hemoptisis 1", "Cancer 1"],
    cutoffs: [">4 TEP likely", "<=4 TEP unlikely", ">6 alta probabilidad"],
    pearl: "Si la probabilidad es alta, vas directo a imagen.",
    trap: "Los dos items de 3 puntos suelen ser la pregunta favorita.",
    prompt: "Di los 2 rubros de 3 puntos y el corte de TEP likely.",
    answer: "Signos de TVP y TEP mas probable; >4 hace TEP likely.",
    searchTerms: ["tep embolia pulmonar angiotac dimero d"]
  },
  {
    id: "wells-tvp",
    name: "Wells para TVP",
    tracks: ["medicina"],
    subtitle: "Trombosis venosa profunda",
    trigger: "Edema unilateral de pierna o dolor en trayecto venoso profundo.",
    hook: "Es la escala que puede restar puntos",
    components: ["Cancer 1", "Paralisis o yeso 1", "Encamamiento o cirugia 1", "Dolor venoso profundo 1", "Pierna entera tumefacta 1", "Pantorrilla >3 cm 1", "Edema con Godet 1", "Colaterales superficiales 1", "TVP previa 1", "Diagnostico alterno tan probable o mas probable -2"],
    cutoffs: [">=2 TVP likely", "<2 TVP unlikely", ">=3 alto riesgo"],
    pearl: "Si preguntan la unica escala que resta puntos, suele ser esta.",
    trap: "No mezcles su item negativo con Wells para TEP.",
    prompt: "Que escala da -2 si hay otro diagnostico igual o mas probable y desde cuando es likely?",
    answer: "Wells para TVP; >=2 puntos la vuelve likely.",
    searchTerms: ["tvp edema unilateral pantorrilla"]
  },
  {
    id: "qsofa",
    name: "qSOFA",
    tracks: ["medicina"],
    subtitle: "Sepsis",
    trigger: "Infeccion sospechada fuera de UCI con necesidad de tamiz rapido.",
    hook: "Respiracion - Presion - Estado mental",
    components: ["FR >=22", "TAS <=100", "Alteracion mental o Glasgow <15"],
    cutoffs: [">=2 alto riesgo"],
    pearl: "Es un tamiz pronostico rapido.",
    trap: "No lleva lactato ni leucocitos.",
    prompt: "Recita los 3 criterios y el corte.",
    answer: "FR >=22, TAS <=100 y alteracion mental; >=2 preocupa por sepsis.",
    searchTerms: ["sepsis choque septico glasgow"]
  },
  {
    id: "glasgow",
    name: "Glasgow",
    tracks: ["cirugia"],
    subtitle: "Trauma y estado de conciencia",
    trigger: "TCE o paciente con disminucion del estado de alerta.",
    hook: "Ocular 4 - Verbal 5 - Motora 6",
    components: ["Apertura ocular 1-4", "Respuesta verbal 1-5", "Respuesta motora 1-6"],
    cutoffs: ["13-15 leve", "9-12 moderado", "<=8 severo"],
    pearl: "Glasgow de 8, intuba.",
    trap: "La respuesta motora es la que mas pesa.",
    prompt: "Di el desglose O-V-M y el corte que obliga a pensar en via aerea.",
    answer: "Ocular 4, verbal 5, motora 6; <=8 obliga a proteger la via aerea.",
    searchTerms: ["tce trauma via aerea"]
  },
  {
    id: "curb65",
    name: "CURB-65",
    tracks: ["medicina"],
    subtitle: "Neumonia adquirida en la comunidad",
    trigger: "NAC cuando te preguntan sitio de manejo y gravedad inicial.",
    hook: "Confusion - Urea - Respiratory rate - Blood pressure - 65",
    components: ["Confusion 1", "Urea >7 mmol/L o BUN >19 mg/dL 1", "FR >=30 1", "TA sistolica <90 o diastolica <=60 1", "Edad >=65 1"],
    cutoffs: ["0-1 ambulatorio", "2 considerar hospital", ">=3 severa y valorar UCI"],
    pearl: "Todos los rubros valen 1 punto.",
    trap: "La U es urea, no saturacion.",
    prompt: "Que significa cada letra de CURB-65 y desde que score piensas en hospital?",
    answer: "Confusion, urea, frecuencia respiratoria, presion arterial y edad; con 2 o mas piensas en hospital.",
    searchTerms: ["nac neumonia urea confusion"]
  },
  {
    id: "cha2ds2-vasc",
    name: "CHA2DS2-VASc",
    tracks: ["medicina"],
    subtitle: "FA y riesgo embolico",
    trigger: "Paciente con fibrilacion auricular no valvular.",
    hook: "Dos componentes valen 2",
    components: ["Insuficiencia cardiaca 1", "Hipertension 1", "Edad >=75 2", "Diabetes 1", "EVC/AIT/TE 2", "Enfermedad vascular 1", "Edad 65-74 1", "Sexo femenino 1"],
    cutoffs: ["Esquema clasico de bancos: hombres >=2 y mujeres >=3 favorecen anticoagulacion"],
    pearl: "En bancos ENARM sigue apareciendo CHA2DS2-VASc; algunas guias recientes europeas migran a CHA2DS2-VA.",
    trap: "Los 2 rubros de 2 puntos son edad >=75 y EVC/AIT previo.",
    prompt: "Cuales son los 2 componentes de 2 puntos y desde cuando anticoagulas en el esquema clasico?",
    answer: "Edad >=75 y EVC/AIT previo; clasico: hombres >=2, mujeres >=3.",
    searchTerms: ["fibrilacion auricular anticoagulacion evc"]
  },
  {
    id: "has-bled",
    name: "HAS-BLED",
    tracks: ["medicina"],
    subtitle: "Riesgo de sangrado en FA",
    trigger: "Paciente con FA cuando te preguntan riesgo de sangrado antes de anticoagular.",
    hook: "Hypertension - Abnormal renal/liver - Stroke - Bleeding - Labile INR - Elderly - Drugs/alcohol",
    components: ["Hipertension 1", "Renal anormal 1", "Hepatica anormal 1", "EVC previo 1", "Sangrado previo 1", "INR labil 1", "Edad >65 1", "Farmacos 1", "Alcohol 1"],
    cutoffs: [">=3 alto riesgo de sangrado"],
    pearl: "Sirve para corregir factores modificables; no para negar anticoagulacion de forma automatica.",
    trap: "A y D pueden sumar 2 porque se separan en renal/hepatica y drogas/alcohol.",
    prompt: "Que significan la L y la D en HAS-BLED y que score es alto riesgo?",
    answer: "Labile INR y drugs/alcohol; >=3 es alto riesgo.",
    searchTerms: ["fibrilacion auricular sangrado inr"]
  },
  {
    id: "child-pugh",
    name: "Child-Pugh",
    tracks: ["medicina"],
    subtitle: "Cirrosis",
    trigger: "Cirrosis cuando te piden severidad funcional y pronostica.",
    hook: "Tres laboratorios + dos clinicos",
    components: ["Bilirrubina 1-3", "Albumina 1-3", "INR o TP 1-3", "Ascitis 1-3", "Encefalopatia 1-3"],
    cutoffs: ["A 5-6", "B 7-9", "C 10-15"],
    pearl: "Si el caso trae ascitis y encefalopatia, ya va empujando a Child-Pugh alto.",
    trap: "No la confundas con MELD.",
    prompt: "Cuales son las 5 variables y como se clasifican A, B y C?",
    answer: "Bilirrubina, albumina, INR, ascitis y encefalopatia; A 5-6, B 7-9, C 10-15.",
    searchTerms: ["cirrosis ascitis encefalopatia higado"]
  },
  {
    id: "bishop",
    name: "Bishop",
    tracks: ["gyo"],
    subtitle: "Induccion del trabajo de parto",
    trigger: "Embarazo a termino o postermino con duda de cuello favorable.",
    hook: "Dilatacion - Borramiento - Estacion - Consistencia - Posicion",
    components: ["Dilatacion", "Borramiento", "Estacion", "Consistencia", "Posicion cervical"],
    cutoffs: ["<6 cuello desfavorable", ">=8 cuello favorable"],
    pearl: "Si Bishop es bajo, primero madura cuello antes de oxitocina.",
    trap: "No es un perfil biofisico; es una escala cervical.",
    prompt: "Que 5 variables valora Bishop y desde que score el cuello es favorable?",
    answer: "Dilatacion, borramiento, estacion, consistencia y posicion; >=8 es favorable.",
    searchTerms: ["induccion oxitocina prostaglandinas cuello uterino"]
  },
  {
    id: "apgar",
    name: "Apgar",
    tracks: ["pedia"],
    subtitle: "Adaptacion neonatal",
    trigger: "Recien nacido al minuto 1 y 5.",
    hook: "Appearance - Pulse - Grimace - Activity - Respiration",
    components: ["Apariencia 0-2", "Pulso 0-2", "Gesticulacion refleja 0-2", "Actividad 0-2", "Respiracion 0-2"],
    cutoffs: ["7-10 buena adaptacion", "4-6 depresion moderada", "0-3 depresion severa"],
    pearl: "Si a los 5 minutos sigue <7, se repite cada 5 minutos hasta 20.",
    trap: "No define por si sola la reanimacion.",
    prompt: "Que significa APGAR y como interpretas 7-10 contra 0-3?",
    answer: "Appearance, Pulse, Grimace, Activity y Respiration; 7-10 buena adaptacion y 0-3 severamente deprimido.",
    searchTerms: ["recien nacido reanimacion neonatal"]
  },
  {
    id: "silverman-andersen",
    name: "Silverman-Andersen",
    tracks: ["pedia"],
    subtitle: "Dificultad respiratoria neonatal",
    trigger: "Recien nacido con quejido, aleteo o tirajes.",
    hook: "Mientras mas alto, peor",
    components: ["Disociacion toracoabdominal 0-2", "Tiraje intercostal 0-2", "Retraccion xifoidea 0-2", "Aleteo nasal 0-2", "Quejido espiratorio 0-2"],
    cutoffs: ["0 sin dificultad", "1-3 leve", "4-6 moderada", "7-10 severa"],
    pearl: "La perla clasica es que esta va al reves del Apgar.",
    trap: "No sirve para estimar edad gestacional.",
    prompt: "Por que Silverman es al reves de Apgar y desde que score hablas de dificultad severa?",
    answer: "Porque mientras mas alto peor; 7-10 es dificultad severa.",
    searchTerms: ["recien nacido tiraje quejido aleteo"]
  },
  {
    id: "ballard",
    name: "Ballard",
    tracks: ["pedia"],
    subtitle: "Edad gestacional neonatal",
    trigger: "RN prematuro o con duda de edad gestacional.",
    hook: "Fisico + neuromuscular",
    components: ["Valora signos fisicos y neuromusculares", "Nueva Ballard: rango aproximado -10 a 50", "Recordatorio de formula: EG = (2 x puntaje + 120) / 5"],
    cutoffs: ["A mayor puntaje, mayor madurez"],
    pearl: "En gran prematuro o con compromiso neurologico, suele ser mejor apuesta que Capurro.",
    trap: "No mezcles la constante 120 con las de Capurro.",
    prompt: "Cuando prefieres Ballard sobre Capurro y que constante no debes olvidar?",
    answer: "Cuando necesitas una valoracion fisica y neuromuscular mas completa; recuerda la constante 120.",
    searchTerms: ["edad gestacional madurez neuromuscular capurro"]
  },
  {
    id: "capurro",
    name: "Capurro",
    tracks: ["pedia"],
    subtitle: "Edad gestacional neonatal",
    trigger: "RN en quien buscas una estimacion rapida de edad gestacional.",
    hook: "La constante clasica mas preguntada es 204",
    components: ["Version A: suele recordarse con (puntaje + 204) / 7", "Version B: suele recordarse con constante 200", "Muchos bancos preguntan la formula mas que el detalle fino de todos los puntos"],
    cutoffs: ["37-41 semanas termino", "<37 pretermino", ">=42 postermino"],
    pearl: "Si el reactivo solo quiere formula, casi siempre busca la constante 204.",
    trap: "Si el RN tiene daño neurologico importante, piensa mejor en Ballard.",
    prompt: "Que formula clasica de Capurro suelen preguntar y cuando deberias pensar mejor en Ballard?",
    answer: "Version A: (puntaje + 204) / 7; si hay compromiso neurologico, piensa en Ballard.",
    searchTerms: ["edad gestacional 204 200 recien nacido"]
  },
  {
    id: "westley",
    name: "Westley",
    tracks: ["pedia"],
    subtitle: "Crup",
    trigger: "Nino con estridor, tos perruna y laringotraqueitis.",
    hook: "Conciencia - Cianosis - Estridor - Entrada de aire - Retracciones",
    components: ["Nivel de conciencia", "Cianosis", "Estridor", "Entrada de aire", "Retracciones"],
    cutoffs: ["<=2 leve", "3-5 moderado", "6-11 severo", ">=12 amenaza de falla respiratoria"],
    pearl: "La perla mas util es que >6 es crup grave.",
    trap: "No la mezcles con Silverman ni con Downes.",
    prompt: "Que 5 dominios integra Westley y desde que score es crup grave?",
    answer: "Conciencia, cianosis, estridor, entrada de aire y retracciones; >6 es crup grave.",
    searchTerms: ["crup laringotraqueitis estridor adrenalina"]
  },
  {
    id: "yesavage",
    name: "Yesavage",
    tracks: ["geria"],
    subtitle: "Depresion geriatrica",
    trigger: "Adulto mayor con anhedonia, aislamiento o pseudodemencia depresiva.",
    hook: "Tamiz de depresion en el adulto mayor",
    components: ["La version corta GDS-15 usa preguntas si o no", "Explora animo, satisfaccion, energia, aburrimiento y desesperanza"],
    cutoffs: ["0-4 dentro de rango", "5-8 probable leve", "9-11 probable moderada", "12-15 probable severa"],
    pearl: "Sirve como tamiz; no sustituye entrevista clinica.",
    trap: "No la confundas con Mini-Mental.",
    prompt: "Para que sirve Yesavage y desde que puntaje orienta a depresion en GDS-15?",
    answer: "Es tamiz de depresion geriatrica; desde 5 puntos orienta a depresion.",
    searchTerms: ["adulto mayor pseudodemencia depresion gds"]
  },
  {
    id: "mmse",
    name: "Mini-Mental",
    tracks: ["geria"],
    subtitle: "Tamiz cognitivo",
    trigger: "Adulto mayor con olvidos, desorientacion o sospecha de deterioro cognitivo.",
    hook: "Orientacion - registro - atencion - recuerdo - lenguaje",
    components: ["Orientacion", "Registro inmediato", "Atencion y calculo", "Recuerdo diferido", "Lenguaje y visoconstruccion"],
    cutoffs: ["24-30 rango usualmente normal", "<24 orienta a deterioro, interpretando escolaridad"],
    pearl: "Es un tamiz practico, no un diagnostico definitivo de demencia.",
    trap: "La escolaridad puede mover mucho la interpretacion.",
    prompt: "Que dominios explora Mini-Mental y cual es su gran limitacion de examen?",
    answer: "Explora orientacion, memoria, atencion, lenguaje y copia; la gran limitacion es la escolaridad.",
    searchTerms: ["demencia cognitivo escolaridad memoria"]
  }
];
