const fs = require('fs');

const newTemario = `    const OFFICIAL_TEMARIO = [
        // ── Ginecología y Obstetricia ──────────────────────────
        "Ginecología y Obstetricia",
        "Introducción: Ciclo genital, Esterilidad y Anticonceptivos",
        "Amenorreas Primarias y Secundarias",
        "Turner", "Morris", "Rokitansky", "Sx de Asherman", "Sx de Sheehan", "Sx de Kallman",
        "Síndrome de Turner", "Síndrome de Morris", "Esterilidad",
        "Anticonceptivos", "Anticoncepción de emergencia",
        "Origen no anatómico: SOP", "Síndrome de ovario poliquístico", "SOP",
        "Endometriosis", "Adenomiosis",
        "Hemorragia Uterina Anormal",
        "Origen anatómico: Miomatosis", "Miomatosis uterina", "Pólipos endometriales",
        "Osteoporosis", "Piso Pélvico", "Síndrome climatérico", "Incontinencia urinaria",
        "Menopausia y Climaterio", "Terapia hormonal de reemplazo",
        "Oncología Ginecología P1: Cáncer de Endometrio y Ovario",
        "Cáncer de endometrio", "Cáncer de ovario", "Tumor germinal de ovario",
        "Oncología Ginecología P2: Tamizaje CACU, CaVa, Vagina y Vulva",
        "Cáncer cervicouterino", "CACU", "NIC", "Colposcopia",
        "Cáncer de vulva", "Cáncer de vagina", "Bartolinitis",
        "Patología Mamaria: Benigna y Cáncer de Mama",
        "Mastopatía fibroquística", "Fibroadenoma", "Cáncer de mama",
        "Mastitis", "Absceso mamario", "Papiloma intraductal",
        "Vaginitis", "Vaginosis bacteriana", "EPI", "Enfermedad Pélvica Inflamatoria",
        "Cervicovaginitis", "Infecciones Ginecología",
        "Cambios Fisiológicos en el Embarazo y Control Prenatal", "Control prenatal",
        "Isoinmunización", "Incompatibilidad Rh", "Factor Rh",
        "Hemorragias del Primer Trimestre",
        "Aborto", "Aborto espontáneo", "Aborto completo", "Aborto incompleto", "Aborto retenido",
        "Ectópico", "Embarazo ectópico",
        "Mola", "Enfermedad trofoblástica gestacional", "Mola hidatidiforme",
        "Hemorragias del Tercer Trimestre",
        "Placenta Previa", "Desprendimiento", "DPPNI", "Vasa previa", "Acretismo placentario",
        "Polihidramnios", "Oligohidramnios", "RCIU", "Restricción del crecimiento intrauterino",
        "Diabetes Gestacional",
        "Trastornos Hipertensivos del Embarazo",
        "Preeclampsia / Eclampsia", "Preeclampsia", "Eclampsia", "Síndrome de HELLP",
        "Colestasis intrahepática del embarazo", "Hiperemesis gravídica",
        "Complicaciones del Embarazo",
        "Trabajo de Parto y Mecanismos del Parto",
        "Inducción, Conducción y Distocias",
        "Parto pretérmino", "RPM", "Ruptura prematura de membranas", "Corioamnionitis",
        "Distocia", "Sufrimiento fetal", "Prolapso de cordón", "Presentación pélvica",
        "Distocia de hombros", "Desproporción cefalopélvica", "Partograma",
        "Sepsis Puerperal e Infección de Herida Quirúrgica",
        "Choque Obstétrico y Hemorragia Obstétrica", "Atonía uterina",
        "Puerperio Fisiológico y Lactancia Materna",
        // ── Pediatría ──────────────────────────
        "Pediatría",
        "Introducción a la Pediatría / Reanimación Neonatal",
        "Capurro", "Ballard", "Silverman-Andersen",
        "Patología Neonatal Metabólica",
        "Hijo de madre diabética", "Electrolitos",
        "Patología Neonatal Infecciosa",
        "Sepsis neonatal", "Onfalitis", "Meningitis neonatal", "Conjuntivitis neonatal",
        "Enterocolitis necrotizante",
        "Patología Respiratoria Neonatal",
        "Membrana hialina", "EMH", "TTRN", "SAM", "Síndrome de aspiración de meconio",
        "Apnea del prematuro", "Persistencia del conducto arterioso",
        "Patología Neonatal Quirúrgica",
        "Malformaciones congénitas", "Onfalocele", "Gastrosquisis", "Atresia esofágica",
        "Hernia diafragmática", "Imperforación anal", "Atresia duodenal",
        "Infecciones TORCH y VIH Pediátrico",
        "Toxoplasmosis congénita", "Citomegalovirus", "Sífilis congénita",
        "Rubéola congénita", "Herpes congénito",
        "Estenosis Hipertrófica de Píloro",
        "Ictericias Neonatales", "Ictericia fisiológica", "Hiperbilirrubinemia",
        "Atresia de vías biliares",
        "Tamiz Metabólico y Auditivo",
        "Hipotiroidismo congénito", "Fenilcetonuria", "Galactosemia",
        "Hiperplasia suprarrenal congénita",
        "Crecimiento y Desarrollo P1",
        "Hitos del desarrollo", "Desarrollo psicomotor",
        "Consulta del niño sano", "Maltrato infantil",
        "Crecimiento y Desarrollo P2",
        "Esquema Nacional de Vacunación",
        "Desnutrición", "Marasmo", "Kwashiorkor", "Obesidad infantil",
        "Déficit de vitamina D", "Raquitismo", "Déficit de vitamina C", "Escorbuto",
        "Muerte súbita del lactante",
        "Vacunación",
        "Patología Gastrointestinal",
        "Reflujo gastroesofágico pediátrico", "Intususcepción", "Invaginación intestinal",
        "Hirschsprung", "Enfermedad de Hirschsprung",
        "Enfermedad Diarreica Aguda y Planes de Hidratación",
        "Plan A de hidratación", "Plan B de hidratación", "Plan C de hidratación",
        "Diarrea Crónica y Síndromes de Mala Absorción",
        "Enfermedad celíaca",
        "Parasitosis en Pediatría",
        "Giardiasis", "Ascariasis", "Oxiuriasis", "Taeniasis", "Amebiasis",
        "Patología Respiratoria del Lactante",
        "Bronquiolitis", "Laringotraqueítis", "Croup", "Epiglotitis", "Tos ferina",
        "Neumonías y sus Complicaciones",
        "Neumonía pediátrica", "Derrame pleural pediátrico", "Empiema pediátrico",
        "Asma Pediátrica", "Crisis asmática pediátrica",
        "Infecciones de Vías Respiratorias Superiores",
        "Otitis media aguda", "Faringoamigdalitis", "Sinusitis pediátrica",
        "Laringotraqueitis bacteriana", "Difteria",
        "Enfermedades Exantemáticas",
        "Sarampión", "Rubéola", "Varicela", "Escarlatina", "Kawasaki",
        "Quinta enfermedad", "Eritema infeccioso", "Sexta enfermedad", "Roséola",
        "Mano pie boca", "Herpangina",
        "Urgencias Pediátricas",
        "Intoxicación por paracetamol", "Intoxicación por ASA",
        "Ingesta de cáusticos", "Ingesta de metales pesados", "Obstrucción de vía aérea",
        "Nefrología y Urología Pediátrica",
        "IVU pediátrica", "Reflujo vesicoureteral",
        "Síndrome nefrótico pediátrico", "Síndrome nefrítico pediátrico",
        "Torsión testicular", "Criptorquidia", "Fimosis", "Parafimosis",
        "Cardiopatías Congénitas",
        "Comunicación interventricular", "CIA", "CIV", "PCA",
        "Tetralogía de Fallot", "Transposición de grandes vasos",
        "Estenosis de arteria pulmonar",
        "Onco-Hematología Pediátrica",
        "Leucemia linfoblástica aguda", "LLA pediátrica",
        "Neuroblastoma", "Nefroblastoma", "Tumor de Wilms",
        "Astrocitoma pediátrico", "Osteosarcoma", "Sarcoma de Ewing",
        "Púrpura de Henoch-Schönlein", "Púrpura trombocitopénica pediátrica",
        "Neuropediatría",
        "Epilepsia pediátrica", "Crisis febriles", "Convulsiones febriles",
        "Hidrocefalia", "Meningitis bacteriana pediátrica",
        "Parálisis cerebral",
        "Ortopedia Pediátrica",
        "Displasia de cadera", "DDC", "Pie plano", "Enfermedad de Perthes",
        "Genu varo", "Genu valgo", "Escoliosis", "Cojera",
        "Genética y Alteraciones Cromosómicas",
        "Síndrome de Down", "Síndrome de Turner pediátrico",
        "Síndrome de Edwards", "Síndrome de Patau", "Síndrome de Klinefelter",
        "Dermatitis atópica", "Impétigo", "Dermatitis del pañal",
        "Dermatitis seborreica", "Molusco contagioso",
        // ── Cirugía ──────────────────────────
        "Cirugía General",
        "Abdomen agudo", "Respuesta metabólica al trauma",
        "Apendicitis Aguda",
        "Patología de Vesícula y Vías Biliares",
        "Colecistitis", "Colelitiasis", "Coledocolitiasis", "Colangitis", "Íleo biliar",
        "Cáncer de vesícula biliar",
        "Pancreatitis Aguda", "Criterios de Ranson", "Pancreatitis Crónica",
        "Patología Quirúrgica de Esófago",
        "Acalasia", "ERGE", "Cáncer de esófago", "Perforación esofágica",
        "Síndrome de Boerhaave", "Desgarro de Mallory-Weiss",
        "Patología de Estómago y Duodeno",
        "Úlcera péptica", "Úlcera perforada", "Gastritis",
        "Hemorragia de tubo digestivo alto", "Zollinger-Ellison",
        "Abdomen Agudo y Oclusión Intestinal",
        "Oclusión intestinal", "Vólvulo de sigmoides", "Vólvulo de ciego",
        "Patología de Intestino Delgado",
        "Divertículo de Meckel", "Enfermedad de Meckel",
        "Patología de Colon y Recto",
        "Diverticulitis", "Diverticulosis", "Enfermedad diverticular",
        "Cáncer colorrectal", "Cáncer de colon", "Cáncer de recto",
        "Colitis ulcerosa", "Enfermedad de Crohn", "Síndrome de Lynch",
        "Patología Perianal",
        "Hemorroides", "Fisura anal", "Fístula anorrectal", "Absceso perirrectal",
        "Isquemia Mesentérica",
        "Cirrosis y sus Complicaciones", "Patología Hepática",
        "Várices esofágicas", "Ascitis", "Encefalopatía hepática",
        "Peritonitis bacteriana espontánea", "Hepatitis viral",
        "Absceso hepático", "NASH", "Enfermedad hepática grasa",
        "Cirrosis hepática", "Hipertensión portal", "Child-Pugh", "MELD",
        "Hernias de la Pared Abdominal",
        "Hernias Inguinales y Crurales",
        "Hernia femoral", "Hernia inguinal", "Hernia umbilical", "Hernia epigástrica",
        "Urología P1: Litiasis Renal y Tumores",
        "Litiasis renal", "Cólico renal", "Nefrolitiasis",
        "Cáncer renal", "Hipernefroma", "Cáncer testicular", "Seminoma",
        "Cáncer de vejiga",
        "Urología P2: Hiperplasia Prostática y Cáncer de Próstata",
        "Hiperplasia prostática benigna", "HPB",
        "Cáncer de próstata", "PSA", "Gleason",
        "Prostatitis", "Epididimitis", "Priapismo", "Varicocele", "Hidrocele",
        "Patología Vascular: Arterial y Venosa",
        "Trombosis venosa profunda", "TVP",
        "Tromboembolia pulmonar", "TEP",
        "Insuficiencia arterial periférica", "Claudicación intermitente",
        "Aneurisma de aorta abdominal",
        "Insuficiencia venosa crónica", "Várices miembros inferiores",
        "ETS / Enfermedades de Transmisión Sexual",
        "Sífilis", "Chancroide", "Linfogranuloma venéreo", "Herpes genital",
        "ATLS P1: Evaluación Inicial y Manejo de Vía Aérea",
        "ABCDE del trauma", "Manejo de vía aérea en trauma", "Choque hemorrágico",
        "ATLS P2: Trauma de Tórax y Abdomen",
        "Trauma craneoencefálico", "TCE", "Hematoma epidural", "Hematoma subdural",
        "Hemorragia subaracnoidea traumática", "Escala de Glasgow",
        "Trauma medular", "Choque neurogénico",
        "Neumotórax a tensión", "Hemotórax masivo", "Taponamiento cardíaco",
        "Tórax inestable", "Volet costal", "Neumotórax abierto",
        "Trauma abdominal", "FAST", "DPL",
        "ATLS P3: Trauma de Extremidades y Casos Especiales",
        "Trauma pelvis", "Fractura de pelvis",
        "Trauma genitourinario", "Ruptura vesical", "Ruptura uretral",
        "Trauma en embarazada", "Trauma pediátrico",
        "Trauma de cuello", "Trauma maxilofacial", "Le Fort",
        "Toxicología",
        "Toxíndromes", "Anticolinérgico", "Colinérgico", "Serotoninérgico", "Opioide",
        "Intoxicación por plomo", "Saturnismo",
        "Mordeduras y Picaduras",
        "Alacranismo", "Loxoscelismo", "Latrodectismo", "Mordedura de serpiente",
        "Mordeduras de mamíferos", "Rabia por mordedura",
        "Quemaduras y Reanimación",
        "Golpe de calor", "Hipotermia", "Quemadura eléctrica",
        "Regla de los 9", "Fórmula de Parkland", "Criterios de envío a unidad de quemados",
        "Oncocirugía P1",
        "Cáncer gástrico", "Cáncer de páncreas",
        "Cáncer de colon y recto", "Cáncer hepático",
        "Oncocirugía P2",
        "Cáncer de mama cirugía", "Cáncer de tiroides",
        "Carcinoma basocelular", "Carcinoma espinocelular", "Melanoma cutáneo",
        "Cáncer de próstata tumores testiculares",
        "Oftalmología P1",
        "Glaucoma", "Catarata", "Retinopatía diabética",
        "Desprendimiento de retina", "Degeneración macular", "Retinopatía del prematuro",
        "Retinoblastoma",
        "Oftalmología P2",
        "Ojo rojo", "Queratitis", "Úlcera corneal", "Uveítis",
        "Glaucoma primario de ángulo abierto", "Estrabismo",
        "Trauma ocular", "Conjuntivitis adulto",
        "Celulitis orbitaria", "Celulitis periorbitaria",
        "Otorrinolaringología P1",
        "Otitis media aguda adulto", "Otitis externa",
        "Hipoacusia", "Otoesclerosis", "Retinopatía del prematuro",
        "Vértigo", "VPPB", "Vértigo postural paroxístico benigno",
        "Enfermedad de Menière", "Neuronitis vestibular",
        "Otorrinolaringología P2",
        "Rinitis", "Rinosinusitis", "Sinusitis crónica", "Amigdalitis",
        "Epistaxis", "Cáncer de laringe", "Papilomatosis laríngea",
        "Absceso periamigdalino",
        "Trauma: Generalidades y Complicaciones",
        "Síndrome compartimental", "Embolia grasa", "Profilaxis antitetánica",
        "Cicatrización", "Fractura en rama verde", "Salter-Harris",
        "Fracturas abiertas", "Gustilo-Anderson",
        "Patología de Extremidad Superior",
        "Fractura de clavícula", "Fractura de escafoides",
        "Fractura supracondílea de húmero", "Fractura de radio distal", "Fractura de Colles",
        "Luxación glenohumeral", "Luxación acromioclavicular",
        "Síndrome del túnel carpiano",
        "Epicondilitis", "Codo de tenista", "Codo de golfista",
        "Tenosinovitis de De Quervain", "Manguito rotador", "Hombro doloroso",
        "Tenosinovitis infecciosa",
        "Patología de Extremidad Inferior",
        "Fractura de cadera", "Luxación de cadera",
        "Fractura de diáfisis femoral",
        "Epifisiolistesis femoral", "Displasia del desarrollo de cadera",
        "Lesión de ligamento cruzado", "LCA", "Meniscopatías",
        "Esguince de tobillo", "Fractura de tobillo Weber",
        // ── Medicina Interna ──────────────────────────
        "Medicina Interna",
        "Infectología: Principios, Antibióticos y Resistencia",
        "SRIS", "Sepsis", "Choque séptico", "Antibióticos",
        "Epidemiología",
        "Tuberculosis", "Tuberculosis pulmonar", "BAAR", "Baciloscopia",
        "VIH / SIDA", "VIH", "SIDA", "Antiretrovirales", "CD4", "Carga viral",
        "Enfermedades transmitidas por Vector",
        "Dengue", "Dengue hemorrágico", "Dengue grave",
        "Zika", "Rickettsia", "Chikungunya", "Paludismo", "Malaria", "Chagas",
        "Zoonosis",
        "Rabia", "Tétanos", "Brucela", "Leptospirosis", "Brucelosis",
        "Patología Fúngica",
        "Candidiasis invasiva", "Histoplasmosis", "Coccidioidomicosis",
        "EPOC / Cáncer de Pulmón", "EPOC",
        "Asma en el adulto", "Crisis asmática adulto",
        "Cáncer de pulmón", "Carcinoma broncogénico",
        "Neumología: Neumonías Ocupacionales",
        "Neumonía adquirida en comunidad", "NAC",
        "Neumonía nosocomial", "Neumonía atípica",
        "Derrame Pleural y Empiema", "Derrame pleural", "Neumotórax espontáneo",
        "Endocrinología: Patología Tiroidea",
        "Hipertiroidismo", "Tormenta tiroidea", "Hipotiroidismo",
        "Tiroiditis de Hashimoto", "Tiroiditis subaguda",
        "Bocio", "Cáncer de tiroides endocrino",
        "Síndrome Metabólico y Dislipidemias",
        "Síndrome metabólico", "Dislipidemia", "Obesidad y sobrepeso",
        "Diabetes Mellitus: Fisiopatología y Diagnóstico",
        "Diabetes tipo 1", "Diabetes tipo 2", "Prediabetes",
        "HBAIC", "glucosa en ayuno",
        "Diabetes Mellitus: Tratamiento",
        "Metformina", "Insulina", "Hipoglucemiantes orales",
        "GLP-1", "SGLT2", "DPP4",
        "Complicaciones Agudas de Diabetes",
        "Cetoacidosis diabética", "Estado hiperosmolar", "Hipoglucemia",
        "Complicaciones Crónicas de Diabetes",
        "Neuropatía diabética", "Nefropatía diabética", "Pie diabético",
        "Patología de Glándula Suprarrenal",
        "Síndrome de Cushing", "Enfermedad de Addison",
        "Feocromocitoma", "Hiperaldosteronismo", "Conn",
        "Insuficiencia suprarrenal",
        "Hematología: Anemias Microcíticas",
        "Anemia ferropénica", "Anemia microcítica", "Ferropenia",
        "Anemia de enfermedad crónica",
        "Hematología: Anemias Macrocíticas y Hemolíticas",
        "Anemia megaloblástica", "Déficit de vitamina B12", "Déficit de folato",
        "Anemia hemolítica", "Drepanocitosis", "Esferocitosis",
        "Hematología: Leucemias y Linfomas",
        "Leucemia mieloide aguda", "Leucemia mieloide crónica",
        "Leucemia linfoblástica aguda", "Leucemia linfocítica crónica",
        "LLA", "LMA", "LLC", "LMC",
        "Linfoma de Hodgkin", "Linfoma no Hodgkin",
        "Mieloma múltiple",
        "Hematología: Alteraciones de la Hemostasia",
        "Púrpura trombocitopénica", "Hemofilia",
        "Coagulación intravascular diseminada", "CID",
        "Anticoagulación", "Heparina", "Warfarina",
        "Gastroenterología: Enfermedad Acidopéptica y H. Pylori",
        "H. pylori", "Helicobacter pylori", "Gastritis crónica",
        "Dispepsia", "Síndrome de Zollinger-Ellison",
        "Gastroenterología: Cirrosis y sus complicaciones",
        "Cirrosis", "Hipertensión portal", "Child-Pugh", "MELD",
        "Reumatología: Artritis Reumatoide",
        "Artritis reumatoide", "Factor reumatoide", "Anti-CCP",
        "Reumatología: Lupus Eritematoso Sistémico",
        "LES", "Lupus eritematoso sistémico", "Anti-DNA", "ANA",
        "Síndrome antifosfolipídico", "Esclerodermia",
        "Síndrome de Sjögren", "Polimiositis", "Dermatomiositis",
        "Reumatología: Vasculitis y Gota",
        "Vasculitis", "Poliarteritis nodosa", "Granulomatosis de Wegener",
        "Gota", "Artritis gotosa", "Hiperuricemia",
        "Artritis psoriásica", "Espondilitis anquilosante",
        "Nefrología: Lesión Renal Aguda",
        "Lesión renal aguda", "LRA", "Creatinina", "KDIGO", "Uremia",
        "Nefrología: Enfermedad Renal Crónica",
        "Enfermedad renal crónica", "ERC", "Diálisis", "Hemodiálisis",
        "Nefrología: Glomerulopatías y Síndromes Nefrótico/Nefrítico",
        "Síndrome nefrótico", "Síndrome nefrítico", "Glomerulonefritis",
        "Trastornos Electrolíticos y Ácido-Base",
        "Acidosis metabólica", "Alcalosis metabólica",
        "Acidosis respiratoria", "Alcalosis respiratoria",
        "Hiponatremia", "Hipernatremia",
        "Hipopotasemia", "Hiperpotasemia",
        "Hipocalcemia", "Hipercalcemia", "Hipomagnesemia",
        "Cardiología: Electrocardiograma básico y Arritmias",
        "ECG", "Electrocardiograma",
        "Fibrilación auricular", "Flutter auricular",
        "Taquicardia supraventricular", "Taquicardia ventricular",
        "Bloqueo AV", "Bloqueo de rama", "WPW",
        "Cardiología: Cardiopatía Isquémica",
        "Angina", "Angina estable", "Angina inestable",
        "Infarto agudo al miocardio", "IAMCEST", "IAMSEST",
        "Síndrome coronario agudo", "Troponina",
        "Cardiología: Insuficiencia Cardíaca",
        "Insuficiencia cardíaca", "ICC", "Fracción de eyección", "BNP",
        "Cardiología: Valvulopatías",
        "Estenosis aórtica", "Insuficiencia aórtica",
        "Estenosis mitral", "Insuficiencia mitral",
        "Prolapso de válvula mitral",
        "Hipertensión Arterial Sistémica",
        "Crisis hipertensiva", "Urgencia hipertensiva", "Emergencia hipertensiva",
        "Hipertensión arterial secundaria",
        "Infecto-Cardio: Endocarditis y Pericarditis",
        "Endocarditis infecciosa", "Pericarditis", "Miocarditis",
        "Derrame pericárdico",
        "ACLS: Reanimación Cardiopulmonar Avanzada",
        "RCP", "ACLS", "BLS", "Desfibrilación",
        "Neurología: Enfermedad Vascular Cerebral",
        "EVC isquémico", "Ictus", "rt-PA", "Ventana terapéutica ictus",
        "Hemorragia intracerebral", "Hemorragia subaracnoidea",
        "TIA", "Ataque isquémico transitorio", "EVC", "ACV",
        "Neurología: Enfermedades Neurodegenerativas",
        "Parkinson", "Alzheimer", "Esclerosis múltiple",
        "Demencia", "Demencia vascular", "Demencia de Lewy",
        "Neurología: Cefaleas",
        "Migraña", "Cefalea tensional", "Cefalea en cluster",
        "Neurología: Crisis Convulsivas y Epilepsia",
        "Epilepsia", "Estado epiléptico", "Crisis convulsiva", "Anticonvulsivos",
        "Dermatología: Tiñas y Acné",
        "Acné", "Tiña pedis", "Tiña corporis", "Tiña versicolor",
        "Psoriasis", "Vitiligo",
        "Dermatología: Lepra y Pitiriasis",
        "Lepra", "Pitiriasis versicolor", "Pitiriasis rosada",
        "Dermatología: Enfermedades Infecciosas de la Piel",
        "Herpes zóster", "Impétigo", "Erisipela", "Celulitis",
        "Onco-Dermatología: Cáncer Basocelular, Espinocelular y Melanoma",
        "Carcinoma basocelular", "Carcinoma espinocelular",
        "Melanoma", "ABCDE de melanoma",
        "Psiquiatría: Depresión y Ansiedad",
        "Depresión mayor", "Ansiedad", "Trastorno de pánico", "Fobia",
        "ISRS", "Antidepresivos",
        "Psiquiatría: Trastornos de la conducta alimentaria / Esquizofrenia",
        "Anorexia nerviosa", "Bulimia nerviosa",
        "Esquizofrenia", "Psicosis", "Antipsicóticos",
        "Trastorno bipolar",
        "Psiquiatría: Adicciones y Trastornos de Personalidad",
        "Dependencia a alcohol", "Dependencia a drogas",
        "Síndrome de abstinencia", "Personalidad límite",
        "Geriatría: Síndromes Geriátricos",
        "Síndrome geriátrico", "Fragilidad", "Delirium",
        "Caídas del anciano", "Polifarmacia", "Depresión geriátrica",
        // ── Término extra ──────────────────────────
        "Conceptos básicos ENARM", "Extra: Clase de Inglés Médico"
    ];`;

let content = fs.readFileSync('D:\\ENARM Lab\\app.js', 'utf8');

// Find the start and end of the OFFICIAL_TEMARIO array
const startMarker = '    const OFFICIAL_TEMARIO = [';
const endMarker = '    ];';

const startIdx = content.indexOf(startMarker);
if (startIdx === -1) {
    console.error('Could not find OFFICIAL_TEMARIO start');
    process.exit(1);
}

// Find the matching end ]
let braceCount = 0;
let endIdx = -1;
for (let i = startIdx; i < content.length; i++) {
    if (content[i] === '[') braceCount++;
    if (content[i] === ']') {
        braceCount--;
        if (braceCount === 0) {
            endIdx = i + 1;
            break;
        }
    }
}

if (endIdx === -1) {
    console.error('Could not find OFFICIAL_TEMARIO end');
    process.exit(1);
}

// Check that next char after ] is ;
const afterClose = content.substring(endIdx, endIdx + 5).trim();
if (afterClose.startsWith(';')) {
    endIdx = content.indexOf(';', endIdx) + 1;
}

const before = content.substring(0, startIdx);
const after = content.substring(endIdx);

fs.writeFileSync('D:\\ENARM Lab\\app.js', before + newTemario + after, 'utf8');
console.log('Successfully updated OFFICIAL_TEMARIO!');
console.log('New temario has', (newTemario.match(/\"/g) || []).length / 2, 'entries approx');
